[package]
name = "csv_processor_wasm"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
# csv = "1.1"
wasm-bindgen = "0.2"
web-sys = {"version" = "0.3", features = ["console"]}
